FROM mips64le/debian:stable-slim
WORKDIR /rebol
ENV REBOL_HOME=/rebol
ENV REBOL_VERSION 3.10.3

ADD https://github.com/Oldes/Rebol3/releases/download/$REBOL_VERSION/rebol3-bulk-linux-mips64le.gz .
RUN gunzip ./rebol* && mv ./rebol* /bin/rebol && chmod +x /bin/rebol

LABEL version="/$REBOL_VERSION"
LABEL description="REBOL (relative expression based object language) console."
LABEL maintainer="oldes.huhuman@gmail.com"

CMD "/bin/rebol"