name: 'Alpine-dev'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Build Alpine arm32v7 image
        run: ./siskin Rebol-Docker.nest alpine-rebol-dev-arm32v7
      - name: Test image
        run: docker run oldes/rebol-dev:alpine-arm32v7 rebol -v
      - name: Push image
        run: docker push oldes/rebol-dev:alpine-arm32v7

      - name: Build Alpine arm64v8 image
        run: ./siskin Rebol-Docker.nest alpine-rebol-dev-arm64v8
      - name: Test image
        run: docker run oldes/rebol-dev:alpine-arm64v8 rebol -v
      - name: Push image
        run: docker push oldes/rebol-dev:alpine-arm64v8

      - name: Build Alpine amd64 image
        run: ./siskin Rebol-Docker.nest alpine-rebol-dev-x64
      - name: Test image
        run: docker run oldes/rebol-dev:alpine-amd64 rebol -v
      - name: Push image
        run: docker push oldes/rebol-dev:alpine-amd64
