name: 'Alpine'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # testing Linux builds...
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm32v6
          - arm32v7
          - arm64v8
          - i386
          - amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.13.0

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Alpine Rebol/Bulk image for ${{ matrix.arch }}
        run: ./siskin Rebol-Docker.nest alpine-rebol-bulk-${{ matrix.arch }}

      - name: Build Alpine Rebol/Dev image for ${{ matrix.arch }}
        run: ./siskin Rebol-Docker.nest alpine-rebol-dev-${{ matrix.arch }}

#      - name: Log in to Github registry
#        # This is where you will update the personal access token to GITHUB_TOKEN
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin


#      - name: Push image to Github Container Registry
#        run: |
#          docker push ghcr.io/oldes/rebol:latest
#          docker push ghcr.io/oldes/rebol:$VER

