name: 'Alpine'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # testing Linux builds...
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: 3.7.1-alpine-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Alpine x86_64 image
        run: |
          cd ./alpine/x86_64/
          docker build -t oldes/rebol:$TAG .
          docker tag  oldes/rebol:$TAG oldes/rebol:$TAG

      - name: Test image
        run: |
          docker run oldes/rebol:$TAG rebol -v
          docker run oldes/rebol:$TAG rebol --usage

      - name: Push image
        run: docker push oldes/rebol:$TAG