name: 'Alpine'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # testing Linux builds...
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      VER: 3.10.3
      TAG: 3.10.3-alpine-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.PACK_TOKEN }}

#      - name: Build Alpine x86_64 image
#        run: |
#          cd ./alpine/amd64/
#          docker build . --tag ghcr.io/oldes/rebol:latest
#          docker tag ghcr.io/oldes/rebol:latest ghcr.io/oldes/rebol:$VER
#
#      - name: Test image - Rebol version
#        run: docker run ghcr.io/oldes/rebol:latest rebol -v
#
#      - name: Test image - Rebol usage
#        run: docker run ghcr.io/oldes/rebol:latest rebol --usage
#
#      - name: Push image to Github Container Registry
#        run: docker push ghcr.io/oldes/rebol:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Alpine x86_64 image
        run: |
          cd ./alpine/amd64/
          docker build -t oldes/rebol:$TAG .
          docker tag docker.io/oldes/rebol:$TAG docker.io/oldes/rebol:alpine
          docker tag docker.io/oldes/rebol:$TAG docker.io/rebol/alpine:latest
#          docker tag docker.io/oldes/rebol:$TAG ghcr.io/oldes/rebol:latest
#          docker tag docker.io/oldes/rebol:$TAG ghcr.io/oldes/rebol:$VER

      - name: Test image - Rebol version
        run: docker run docker.io/oldes/rebol:$TAG rebol -v

      - name: Test image - Rebol usage
        run: docker run docker.io/oldes/rebol:$TAG rebol --usage

      - name: Push image to Oldes repository
        run: |
          docker push docker.io/oldes/rebol:$TAG
          docker push docker.io/oldes/rebol:alpine

      - name: Push image to Rebol repository
        run: docker push docker.io/rebol/alpine

#      - name: Log in to Github registry
#        # This is where you will update the personal access token to GITHUB_TOKEN
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin


#      - name: Push image to Github Container Registry
#        run: |
#          docker push ghcr.io/oldes/rebol:latest
#          docker push ghcr.io/oldes/rebol:$VER

