name: 'Build Alpine Rebol'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Rebol-Alpine-x86:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Download Alpine-i386 Rebol-dev container
        run: docker pull oldes/rebol-dev:alpine-i386 

      - name: Build all Rebol versions for alpine-i386
        run: ./siskin Rebol-Docker.nest rebol-alpine-x86

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Alpine-Linux
          path: ./alpine/x86/*.gz

  Rebol-Alpine-x86_64:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Download Alpine-amd64 Rebol-dev container
        run: docker pull oldes/rebol-dev:alpine-amd64 

      - name: Build all Rebol versions for alpine-amd64
        run: ./siskin Rebol-Docker.nest rebol-alpine-x64

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Alpine-Linux
          path: ./alpine/amd64/*.gz


  Rebol-Alpine-arm32v6:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Download Alpine-arm32v6 Rebol-dev container
        run: docker pull oldes/rebol-dev:alpine-arm32v6

      - name: Build all Rebol versions for alpine-arm32v6
        run: ./siskin Rebol-Docker.nest rebol-alpine-arm32v6

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Alpine-Linux
          path: ./alpine/arm32v6/*.gz

  Rebol-Alpine-arm32v7:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Download Alpine-arm32v7 Rebol-dev container
        run: docker pull oldes/rebol-dev:alpine-arm32v7 

      - name: Build all Rebol versions for alpine-arm32v7
        run: ./siskin Rebol-Docker.nest rebol-alpine-arm32v7

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Alpine-Linux
          path: ./alpine/arm32v7/*.gz


  Rebol-Alpine-arm64v8:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.7.2

      - name: Download Alpine-arm64v8 Rebol-dev container
        run: docker pull oldes/rebol-dev:alpine-arm64v8 

      - name: Build all Rebol versions for alpine-arm64v8
        run: ./siskin Rebol-Docker.nest rebol-alpine-arm64v8

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Alpine-Linux
          path: ./alpine/arm64v8/*.gz
