name: 'Build test'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # testing Linux builds...
  linux-test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#      - name: Install Siskin Builder
#        uses: oldes/install-siskin@v0.7.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker info
        run: docker version && docker info


      - name: Download Alpine-arm32v7 Rebol-dev container
        run: docker pull --platform linux/arm/v7 oldes/rebol-dev:alpine-arm32v7 

      - name: Rebol version on alpine-arm32v7
        run: docker run --platform linux/arm/v7 --rm oldes/rebol-dev:alpine-arm32v7 /bin/rebol -v 

#      - name: Build all Rebol versions for alpine-arm32v7
#        run: ./siskin Rebol-Docker.nest rebol-alpine-arm32v7

