name: 'Build Alpine Rebol'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # testing Linux builds...
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      TAG: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Alpine x86_64 image
        run: |
          cd ./alpine/x86_64/
          docker build -f Dockerfile-dev -t oldes/rebol-dev:$TAG .

      - name: Build all Rebol versions
        run: |
          cd ./alpine/x86_64/
          chmod +x ./build-all.sh
          docker run -v $PWD:/out/ -it --rm oldes/rebol-dev /out/build-all.sh

      - name: Create archives from each version
        run: |
          cd ./alpine/x86_64/
          gzip -9 ./rebol3-base-x64-musl
          gzip -9 ./rebol3-core-x64-musl
          gzip -9 ./rebol3-bulk-x64-musl

      - uses: actions/upload-artifact@v2
        with:
          name: Red-Linux
          path: ./alpine/x86_64/*.gz
