name: 'CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      push:
        describe: "Push to Docker HUB"
        required: true
        default: 'true'
      rebol_version:
        description: 'Rebol Version (add - at tail if used!)'
        required: true
        default: ''

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_version:
          - alpine
          - clearlinux
          - debian
          - ubuntu
          #TODO: - tinycore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: |
          cd ./${{ matrix.os_version }}/x86_64/
          docker build -t oldes/rebol:${{ matrix.os_version }} .
          docker tag  oldes/rebol:${{ matrix.os_version }} oldes/rebol:${{ matrix.os_version }}

      - name: Test image
        run: |
          docker run oldes/rebol:${{ matrix.os_version }} rebol -v
          docker run oldes/rebol:${{ matrix.os_version }} rebol --usage

      - name: Push image
        if: ${{ github.event.inputs.push == 'true' }}
        run: docker push oldes/rebol:${{ github.event.inputs.rebol_version}}${{ matrix.os_version }}