FROM oldes/rebol:alpine-amd64

RUN apk update && apk add git build-base linux-headers

RUN git clone https://github.com/Siskin-framework/Builder.git --depth 1

LABEL description="REBOL (relative expression based object language) build environment."
LABEL maintainer="oldes.huhuman@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/Oldes/Rebol-Docker"

CMD "/bin/sh"